# Generated by Django 3.1.2 on 2020-10-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert_coin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='AlertCoin',
        ),
    ]
